apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
  name: vote-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
      

